# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
